#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" != "--system" || -z "${2:-}" || "${3:-}" != "--events" || -z "${4:-}" || "${5:-}" != "--exit-code" || -z "${6:-}" ]]; then
  echo "usage: validate-events.sh --system SYSTEM --events FILE --exit-code CODE" >&2
  exit 64
fi
system=$2
events=$4
exit_code=$6

classification=complete
detail="event stream and requested model passed runner checks"

if [[ ! -s "${events}" ]]; then
  classification=infrastructure_failure
  detail="event stream is empty"
elif ! jq -e . "${events}" >/dev/null 2>&1; then
  classification=infrastructure_failure
  detail="event stream contains invalid JSONL"
elif [[ "${system}" == claude ]]; then
  if jq -e 'select(.type == "system" and (.subtype == "model_refusal_fallback" or .subtype == "model_fallback" or .subtype == "model_consent_fallback"))' "${events}" >/dev/null; then
    classification=model_contamination
    detail="Claude event stream contains an automatic model fallback"
  elif jq -e 'select(.type == "system" and .subtype == "model_refusal_no_fallback")' "${events}" >/dev/null; then
    classification=model_refusal
    detail="Fable 5 refused and fail-closed without fallback"
  elif jq -e 'select(.type == "assistant" and .message.model != null and .message.model != "<synthetic>" and (.message.model | contains("fable-5") | not))' "${events}" >/dev/null; then
    classification=model_contamination
    detail="assistant output was generated by a model other than Fable 5"
  elif [[ "${exit_code}" -eq 124 || "${exit_code}" -eq 137 ]]; then
    classification=timeout
    detail="hard wall-clock limit reached"
  elif [[ "${exit_code}" -ne 0 ]] && jq -e 'select(.type == "assistant" and .message.model != null and .message.model != "<synthetic>")' "${events}" >/dev/null; then
    classification=agent_failure
    detail="model produced a real turn but the native CLI exited nonzero"
  elif [[ "${exit_code}" -ne 0 ]]; then
    classification=infrastructure_failure
    detail="CLI or isolation process exited nonzero"
  elif ! jq -e 'select(.type == "assistant" and .message.model != null and .message.model != "<synthetic>")' "${events}" >/dev/null; then
    classification=infrastructure_failure
    detail="Claude exited without a real assistant turn"
  fi
elif [[ "${exit_code}" -eq 124 || "${exit_code}" -eq 137 ]]; then
  classification=timeout
  detail="hard wall-clock limit reached"
elif [[ "${exit_code}" -ne 0 ]] && jq -e 'select(.type == "item.completed" and .item.type == "agent_message")' "${events}" >/dev/null; then
  classification=agent_failure
  detail="model produced a real turn but the native CLI exited nonzero"
elif [[ "${exit_code}" -ne 0 ]]; then
  classification=infrastructure_failure
  detail="CLI or isolation process exited nonzero"
elif ! jq -e 'select(.type == "item.completed" and .item.type == "agent_message")' "${events}" >/dev/null; then
  classification=infrastructure_failure
  detail="Codex exited without a real assistant turn"
fi

jq -n \
  --arg classification "${classification}" \
  --arg detail "${detail}" \
  --argjson exit_code "${exit_code}" \
  '{classification: $classification, detail: $detail, exit_code: $exit_code}'
